{{- range .Values.logicalReplication.externalClusters }}
{{- if and .passwordSecret .passwordSecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-logical-replication-%s-password" (include "cluster.fullname" $) .name) .passwordSecret.name }}
  namespace: {{ include "cluster.namespace" $ }}
  labels:
  {{- include "cluster.labels" $ | nindent 4 }}
  {{- with $.Values.cluster.additionalLabels }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ .passwordSecret.key }}: {{ required (printf ".Values.logicalReplication.externalClusters[%s].passwordSecret.value required when creating a password secret." .name) .passwordSecret.value | b64enc | quote }}
{{- end }}
{{- end }}
